version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Senha#1234"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - FluxoDeCaixa-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P 'Senha#1234' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

  api:
    build:
      context: .
      dockerfile: FluxoDeCaixa.API/Dockerfile
    container_name: FluxoDeCaixa-api
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EmpresaDB;User Id=sa;Password=Senha#1234;TrustServerCertificate=True"
    networks:
      - FluxoDeCaixa-network

  frontend:
    build:
      context: ../FluxoDeCaixa-frontend
      dockerfile: Dockerfile
    container_name: FluxoDeCaixa-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - FluxoDeCaixa-network

networks:
  FluxoDeCaixa-network:
    driver: bridge

volumes:
  sqlserver-data:
  
